baseURL = "https://kind-joliot-1699fe.netlify.com"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "jelenicTheme"
pluralizelisttitles = false

[taxonomies]
  tag="tags"
  category="categories"
  mood = "moods"
  job = "jobs"
